USE ROLE ROLE_FIN_DATA_ENGINEER;
USE DATABASE FIN_DATA_DEV;
CREATE SCHEMA IF NOT EXISTS SILVER;
USE SCHEMA SILVER;

-- Canonical Product Table
CREATE TABLE IF NOT EXISTS SILVER.PRODUCTS (
    PRODUCT_KEY        NUMBER IDENTITY(1,1),
    PRODUCT_ID         VARCHAR(50),
    PRODUCT_NAME       VARCHAR(255),
    CATEGORY           VARCHAR(100),
    UNIT_PRICE         NUMBER(15,2),
    CURRENCY           VARCHAR(50),
    IS_ACTIVE          BOOLEAN,
    SOURCE_SYSTEM      VARCHAR(50),
    TRACKINGHASH       VARCHAR(150),
    INGESTED_AT        TIMESTAMP_NTZ
);

-- Unified Canonical Customer Table
CREATE TABLE IF NOT EXISTS SILVER.CUSTOMERS (
    CUSTOMER_KEY       NUMBER IDENTITY(1,1),
    CUSTOMER_ID        VARCHAR(50),
    FIRST_NAME         VARCHAR(100),
    LAST_NAME          VARCHAR(100),
    EMAIL              VARCHAR(255),
    LOYALTY_TIER       VARCHAR(50),
    SIGNUP_SOURCE      VARCHAR(50),
    SEGMENT            VARCHAR(50),
    IS_ACTIVE          BOOLEAN,
    SOURCE_SYSTEM      VARCHAR(50),
    TRACKINGHASH       VARCHAR(150),
    INGESTED_AT        TIMESTAMP_NTZ,
    PRIMARY KEY (CUSTOMER_KEY)
);

-- Canonical Orders Table
CREATE TABLE IF NOT EXISTS SILVER.ORDERS (
    ORDER_KEY          NUMBER IDENTITY(1,1),
    ORDER_ID           VARCHAR(50),
    CUSTOMER_ID        VARCHAR(50),
    ORDER_DATE         DATE,
    ORDER_STATUS       VARCHAR(50),
    CHANNEL            VARCHAR(50),
    SOURCE_SYSTEM      VARCHAR(50),
    TRACKINGHASH       VARCHAR(150),
    INGESTED_AT        TIMESTAMP_NTZ,
    PRIMARY KEY (ORDER_KEY)
);

-- Canonical Transactions Table
CREATE TABLE IF NOT EXISTS SILVER.TRANSACTIONS (
    TXN_KEY            NUMBER IDENTITY(1,1),
    TXN_ID             VARCHAR(50),
    ORDER_KEY          VARCHAR(50),
    ORDER_ID           VARCHAR(50),
    ORDER_DATE         DATE,
    CUSTOMER_ID        VARCHAR(50),
    FIRST_NAME         VARCHAR(100),
    LAST_NAME          VARCHAR(100),
    EMAIL              VARCHAR(255),
    NOTE               VARCHAR(255),
    PRODUCT_ID         VARCHAR(50),
    PRODUCT_DESCRIPTION VARCHAR(255),
    QUANTITY           NUMBER(10,2),
    UNIT_PRICE         NUMBER(15,2),
    UNIT_PRICE_CURRENCY VARCHAR(50),
    PAYMENT_METHOD     VARCHAR(50),
    AMOUNT             NUMBER(15,2),
    AMOUNT_CURRENCY    VARCHAR(50),
    SOURCE_SYSTEM      VARCHAR(50),
    TRACKINGHASH       VARCHAR(150),
    INGESTED_AT        TIMESTAMP_NTZ,
    PRIMARY KEY (TXN_KEY)
);

-- Canonical Payments Table
CREATE TABLE IF NOT EXISTS SILVER.PAYMENTS (
    PAYMENT_KEY        NUMBER IDENTITY(1,1),
    PAYMENT_ID         VARCHAR(50),
    ORDER_ID           VARCHAR(50),
    PAYMENT_METHOD     VARCHAR(50),
    AMOUNT             NUMBER(15,2),
    CURRENCY           VARCHAR(50),
    PAYMENT_STATUS     VARCHAR(20),
    SOURCE_SYSTEM      VARCHAR(50),
    TRACKINGHASH       VARCHAR(150),
    INGESTED_AT        TIMESTAMP_NTZ,
    PRIMARY KEY (PAYMENT_KEY)
);