USE ROLE ROLE_FIN_DATA_ENGINEER;
USE DATABASE FIN_DATA_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE PROCEDURE RAW.SP_INGEST_ORDERS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    COPY INTO RAW.ORDERS_LANDING (SOURCE_PATH, RAW_CONTENT)
    FROM (SELECT METADATA$FILENAME, OBJECT_CONSTRUCT(*) FROM @stg_finance_azure/)
    FILE_FORMAT = (FORMAT_NAME = 'ff_csv_header') PATTERN = '.*/order.*\.csv';
    
    RETURN 'Success: Orders Ingested';
END;
$$;