USE ROLE ROLE_FIN_DATA_ENGINEER;
USE DATABASE FIN_DATA_DEV;
USE SCHEMA RAW;

CREATE OR REPLACE PROCEDURE RAW.SP_INGEST_TRANSACTIONS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Client A: XML
COPY INTO RAW.TRANSACTIONS_LANDING (SOURCE_PATH, RAW_CONTENT)
    FROM (
        SELECT 
            METADATA$FILENAME,
            PARSE_XML(REGEXP_REPLACE($1, '^[^<]*', '')) 
        FROM @stg_finance_azure/client_a/
        (FILE_FORMAT => 'RAW.FF_TEXT_RAW')
    )
    PATTERN = '.*\.xml'
    ON_ERROR = 'CONTINUE';

    -- Client A: TXT
    COPY INTO RAW.TRANSACTIONS_LANDING (SOURCE_PATH, RAW_CONTENT)
    FROM (SELECT METADATA$FILENAME, TO_VARIANT($1) FROM @stg_finance_azure/client_a/)
    FILE_FORMAT = (FORMAT_NAME = 'ff_text') PATTERN = '.*\.txt';

    -- Client C: JSON
    COPY INTO RAW.TRANSACTIONS_LANDING (SOURCE_PATH, RAW_CONTENT)
    FROM (SELECT METADATA$FILENAME, $1 FROM @stg_finance_azure/client_c/)
    FILE_FORMAT = (FORMAT_NAME = 'ff_json') PATTERN = '.*\.json';

    RETURN 'Success: Transactions Ingested';
END;
$$;