USE ROLE ROLE_FIN_DATA_ENGINEER;
USE DATABASE FIN_DATA_DEV;
CREATE SCHEMA IF NOT EXISTS RAW;
USE SCHEMA RAW;

-- 1. FILE FORMATS (Data Parsers)
CREATE OR REPLACE FILE FORMAT ff_csv_header
  TYPE = CSV 
  SKIP_HEADER = 2
  NULL_IF = ('', 'NULL') 
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE FILE FORMAT ff_xml
  TYPE = XML 
  STRIP_OUTER_ELEMENT = FALSE;

CREATE OR REPLACE FILE FORMAT ff_json
  TYPE = JSON 
  STRIP_OUTER_ARRAY = TRUE;

-- 2. EXTERNAL STAGE (Pointer to Azure)
CREATE OR REPLACE STAGE stg_finance_azure
  STORAGE_INTEGRATION = azure_finance_int
  URL = 'azure://stfinancedata2026.blob.core.windows.net/inbound-files/';

-- 3. BRONZE TABLES (ELT Raw Storage & Lineage)
-- Entity: Transactions (Handles XML, JSON, TXT)
CREATE OR REPLACE TABLE RAW.TRANSACTIONS_LANDING (
    SOURCE_PATH STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Entity: Customers (Handles CSV from any client)
CREATE OR REPLACE TABLE RAW.CUSTOMERS_LANDING (
    SOURCE_PATH STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Entity: Payments
CREATE OR REPLACE TABLE RAW.PAYMENTS_LANDING (
    SOURCE_PATH STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Entity: Orders
CREATE OR REPLACE TABLE RAW.ORDERS_LANDING (
    SOURCE_PATH STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Entity: Products
CREATE OR REPLACE TABLE RAW.PRODUCTS_LANDING (
    SOURCE_PATH STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);