USE ROLE ROLE_FIN_DATA_ENGINEER;
USE DATABASE FIN_DATA_DEV;
CREATE SCHEMA IF NOT EXISTS RAW;

-- 1. FILE FORMATS (Data Parsers)
CREATE OR REPLACE FILE FORMAT ff_csv_header
  TYPE = CSV 
  SKIP_HEADER = 2
  NULL_IF = ('', 'NULL') 
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE FILE FORMAT ff_xml
  TYPE = XML 
  STRIP_OUTER_ELEMENT = FALSE;

CREATE OR REPLACE FILE FORMAT ff_json
  TYPE = JSON 
  STRIP_OUTER_ARRAY = TRUE;

-- 2. EXTERNAL STAGE (Pointer to Azure)
CREATE OR REPLACE STAGE stg_finance_azure
  STORAGE_INTEGRATION = azure_finance_int
  URL = 'azure://stfinancedata2026.blob.core.windows.net/inbound-files/';

-- 3. BRONZE TABLES (ELT Raw Storage & Lineage)
CREATE OR REPLACE TABLE RAW.CLIENT_A (
    FILE_NAME STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CLIENT_B (
    FILE_NAME STRING,
    RAW_CONTENT VARIANT,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS_CSV (
    CLIENT_SOURCE STRING,
    FILE_NAME STRING,
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    LOYALTY_TIER STRING,
    SIGNUP_SOURCE STRING,
    IS_ACTIVE STRING, 
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.ORDERS_CSV (
    CLIENT_SOURCE STRING,
    FILE_NAME STRING,
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE STRING,
    ORDER_STATUS STRING,
    CHANNEL STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTS_CSV (
    CLIENT_SOURCE STRING,
    FILE_NAME STRING,
    SKU STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    UNIT_PRICE STRING,
    CURRENCY STRING,
    IS_ACTIVE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PAYMENTS_CSV (
    CLIENT_SOURCE STRING,
    FILE_NAME STRING,
    PAYMENT_ID STRING,
    TRANSACTION_ID STRING,
    PAYMENT_METHOD STRING,
    STATUS STRING,
    AMOUNT STRING,
    CURRENCY STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);