----- 1. Create the physical infrastructure
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FIN_DATA_DEV;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.GOLD;

----- 2. Create Azure Integration
USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION IF NOT EXISTS azure_finance_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '<tu_azure_tenant_id>'
  STORAGE_ALLOWED_LOCATIONS = ('azure://stfinancedata2026.blob.core.windows.net/inbound-files/');

----- 3. Create roles and assign permissions
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ROLE_FIN_DATA_ENGINEER;

GRANT USAGE, OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT OWNERSHIP ON DATABASE FIN_DATA_DEV TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIN_DATA_DEV.RAW TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;

GRANT USAGE ON INTEGRATION azure_finance_int TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT ROLE ROLE_FIN_DATA_ENGINEER TO ROLE SYSADMIN;