----- 1. Create the physical infrastructure
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS FIN_DATA_DEV;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.SILVER;
CREATE SCHEMA IF NOT EXISTS FIN_DATA_DEV.GOLD;

----- 2. Create Azure Integration
USE ROLE ACCOUNTADMIN;
CREATE STORAGE INTEGRATION IF NOT EXISTS azure_finance_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'AZURE'
  ENABLED = TRUE
  AZURE_TENANT_ID = '20452560-2ab8-4a92-aaad-4a1653c4dfa0'
  STORAGE_ALLOWED_LOCATIONS = ('azure://stfinancedata2026.blob.core.windows.net/inbound-files/');