----- 1. RBAC (Role-Based Access Control)
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS ROLE_FIN_DATA_ENGINEER;

GRANT USAGE, OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT OWNERSHIP ON DATABASE FIN_DATA_DEV TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIN_DATA_DEV.RAW TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ENGINEER REVOKE CURRENT GRANTS;

GRANT USAGE ON INTEGRATION azure_finance_int TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT ROLE ROLE_FIN_DATA_ENGINEER TO ROLE SYSADMIN;

----- 2. Data Masking Policy (PII Emails)
USE ROLE ROLE_FIN_DATA_ENGINEER; 
USE DATABASE FIN_DATA_DEV;
USE SCHEMA SILVER;

CREATE MASKING POLICY IF NOT EXISTS mask_pii_email AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_FIN_DATA_ENGINEER', 'ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE REGEXP_REPLACE(val, '(.).*(.@.*)', '\\1***\\2')
  END;

----- 3. Row Access Policies
CREATE TABLE IF NOT EXISTS SILVER.SECURITY_ENTITLEMENTS (
    USER_NAME VARCHAR,
    ALLOWED_SOURCE_SYSTEM VARCHAR
);

CREATE ROW ACCESS POLICY IF NOT EXISTS row_policy_source_system AS (source_system VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ROLE_FIN_DATA_ENGINEER', 'SYSADMIN')
  OR
  EXISTS (
      SELECT 1 FROM SILVER.SECURITY_ENTITLEMENTS
      WHERE USER_NAME = CURRENT_USER()
      AND ALLOWED_SOURCE_SYSTEM = source_system
  );

----- 4. Object tagging
CREATE TAG IF NOT EXISTS pii_data_tag;

ALTER TAG pii_data_tag SET MASKING POLICY mask_pii_email FORCE;