----- 1. RBAC (Role-Based Access Control)
USE ROLE SECURITYADMIN;

-- Create functional roles
CREATE ROLE IF NOT EXISTS ROLE_FIN_DATA_ENGINEER; -- Para crear/modificar pipelines
CREATE ROLE IF NOT EXISTS ROLE_FIN_DATA_ANALYST;  -- Para leer la capa Gold/Silver

-- Hierarchy (Inheritance)
GRANT ROLE ROLE_FIN_DATA_ANALYST TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT ROLE ROLE_FIN_DATA_ENGINEER TO ROLE SYSADMIN;

-- Privilege Assignment
GRANT USAGE ON DATABASE FIN_DATA_DEV TO ROLE ROLE_FIN_DATA_ANALYST;
GRANT USAGE ON SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ANALYST;

GRANT ALL PRIVILEGES ON SCHEMA FIN_DATA_DEV.RAW TO ROLE ROLE_FIN_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA FIN_DATA_DEV.SILVER TO ROLE ROLE_FIN_DATA_ENGINEER;

----- 2. Data Masking Policy para PII (Emails) - Column level
USE ROLE SYSADMIN;
USE DATABASE FIN_DATA_DEV;
USE SCHEMA SILVER;

CREATE OR REPLACE MASKING POLICY mask_pii_email AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_FIN_DATA_ENGINEER', 'ACCOUNTADMIN', 'SYSADMIN') THEN val
    ELSE REGEXP_REPLACE(val, '(.).*(.@.*)', '\\1***\\2')
  END;

-- Apply the policy to the Canonical Model table (DIM_CUSTOMER)
ALTER TABLE SILVER.DIM_CUSTOMER 
  MODIFY COLUMN EMAIL SET MASKING POLICY mask_pii_email;


----- 3. Row Access Policies
CREATE OR REPLACE TABLE SILVER.SECURITY_ENTITLEMENTS (
    USER_NAME VARCHAR,
    ALLOWED_SOURCE_SYSTEM VARCHAR
);

-- Create the Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY row_policy_source_system AS (source_system VARCHAR) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ROLE_FIN_DATA_ENGINEER', 'SYSADMIN')
  OR
  EXISTS (
      SELECT 1 FROM SILVER.SECURITY_ENTITLEMENTS
      WHERE USER_NAME = CURRENT_USER()
      AND ALLOWED_SOURCE_SYSTEM = source_system
  );

-- Apply to Canonical tables
ALTER TABLE SILVER.FACT_TRANSACTION 
  ADD ROW ACCESS POLICY row_policy_source_system ON (SOURCE_SYSTEM);


----- 4. Object tagging
CREATE OR REPLACE TAG pii_data_tag;

-- Assign the masking policy to the Tag directly
ALTER TAG pii_data_tag SET MASKING POLICY mask_pii_email;

-- CREATE TABLE SILVER.NEW_TABLE ( email VARCHAR WITH TAG (pii_data_tag = 'email') );