USE DATABASE FIN_DATA_DEV;
USE SCHEMA RAW;

-- Documented Master Task pointing to the Orchestrator SP
CREATE OR REPLACE TASK TSK_BRONZE_MASTER
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = '60 MINUTE'
AS
    CALL RAW.SP_BRONZE_ORCHESTRATOR();

CREATE OR REPLACE TASK TSK_SILVER_MASTER 
    WAREHOUSE = 'COMPUTE_WH'
    AFTER TSK_BRONZE_MASTER 
AS
    CALL SILVER.SP_SILVER_ORCHESTRATOR();

-- Enable the schedule immediately
ALTER TASK RAW.TSK_BRONZE_MASTER SUSPEND;
ALTER TASK RAW.TSK_SILVER_MASTER RESUME;
ALTER TASK RAW.TSK_BRONZE_MASTER RESUME;

