USE DATABASE FIN_DATA_DEV;
USE SCHEMA RAW;

-- Documented Master Task pointing to the Orchestrator SP
CREATE OR REPLACE TASK TSK_BRONZE_MASTER
    WAREHOUSE = 'COMPUTE_WH'
    SCHEDULE = '60 MINUTE'
AS
    CALL RAW.SP_BRONZE_ORCHESTRATOR();

CREATE OR REPLACE TASK SILVER.TSK_SILVER_CUSTOMERS
    WAREHOUSE = 'COMPUTE_WH'
    AFTER RAW.TSK_BRONZE_MASTER 
AS
    CALL SILVER.SP_SILVER_CUSTOMERS();

-- Enable the schedule immediately
ALTER TASK RAW.TSK_BRONZE_MASTER RESUME;
ALTER TASK SILVER.TSK_SILVER_CUSTOMERS RESUME;

