CREATE OR REPLACE PROCEDURE RAW.SP_BRONZE_ORCHESTRATOR()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    --CALL RAW.SP_INGEST_TRANSACTIONS();
    CALL RAW.SP_INGEST_CUSTOMERS();
    CALL RAW.SP_INGEST_PAYMENTS();
    CALL RAW.SP_INGEST_ORDERS();
    CALL RAW.SP_INGEST_PRODUCTS();
    
    RETURN 'Bronze Layer Ingestion Completed Successfully';
END;
$$;