CREATE OR REPLACE PROCEDURE RAW.SP_BRONZE_ORCHESTRATOR()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    CALL RAW.SP_INGEST_CUSTOMERS_CLIENT_A();
    CALL RAW.SP_INGEST_CUSTOMERS_CLIENT_C();
    CALL RAW.SP_INGEST_PAYMENTS_CLIENT_C();
    CALL RAW.SP_INGEST_ORDERS_CLIENT_A();
    CALL RAW.SP_INGEST_ORDERS_CLIENT_C();
    CALL RAW.SP_INGEST_PRODUCTS();
    CALL RAW.SP_INGEST_TRANSACTIONS_CLIENT_A();
    
    RETURN 'Bronze Layer Ingestion Completed Successfully';
END;
$$;