CREATE OR REPLACE PROCEDURE SILVER.SP_SILVER_ORCHESTRATOR()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    CALL SILVER.SP_SILVER_CUSTOMERS();
    CALL SILVER.SP_SILVER_ORDERS();
    CALL SILVER.SP_SILVER_PRODUCTS();
    
    RETURN 'Silver Layer Ingestion Completed Successfully';
END;
$$;