name: Snowflake DataOps Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-database-objects:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0

      - name: Generate Snowflake Configuration File
        run: |
          mkdir -p ~/.snowflake
          cat << EOF > ~/.snowflake/config.toml
          [connections.bootstrap]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "ACCOUNTADMIN"

          [connections.dev]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "ROLE_FIN_DATA_ENGINEER"
          warehouse = "COMPUTE_WH"
          database = "FIN_DATA_DEV"
          EOF

          chmod 0600 ~/.snowflake/config.toml

      - name: Bootstrap Account Setup
        run: snow sql -f config/account_setup.sql -c bootstrap

      - name: Deploy DataOps Project
        run: snow deploy --project config/ --env dev -c dev